package com.freedu.kidslearn.core.audio

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Maps an exact `(text, locale)` narration line to its bundled asset file.
 *
 * The table is generated by `tools/generate_narration.py` (which parses the
 * content catalogs, so the manifest always matches the exact strings the UI
 * speaks) and shipped in `assets/narration/manifest.json`. A missing entry is
 * not an error: [BundledSpeechPlayer] falls back to system TTS for lines with
 * no bundled clip (e.g. dynamic "3 plus 2" prompts).
 */
interface NarrationManifest {
    /** Returns the asset file name (e.g. `"bn_l12.mp3"`), or null if unbundled. */
    fun fileFor(text: String, localeTag: String): String?
}

/**
 * Reads the generated manifest from APK assets.
 *
 * Loaded lazily on first Listen tap rather than at startup, and any failure
 * (regenerated APK, corrupt JSON) degrades to an empty table - every line then
 * takes the system-TTS path, exactly as before bundling existed.
 */
@Singleton
class AssetNarrationManifest @Inject constructor(
    @param:ApplicationContext private val context: Context,
) : NarrationManifest {

    private val table: Map<String, String> by lazy {
        runCatching {
            context.assets.open(MANIFEST_PATH).bufferedReader().use { reader ->
                // org.json ships with the platform; no extra dependency.
                val entries = org.json.JSONObject(reader.readText())
                    .getJSONArray("entries")
                buildMap(entries.length()) {
                    for (i in 0 until entries.length()) {
                        val entry = entries.getJSONObject(i)
                        put(
                            key(entry.getString("text"), entry.getString("locale")),
                            entry.getString("file"),
                        )
                    }
                }
            }
        }.getOrDefault(emptyMap())
    }

    override fun fileFor(text: String, localeTag: String): String? =
        table[key(text, localeTag)]

    private companion object {
        const val MANIFEST_PATH = "narration/manifest.json"

        fun key(text: String, localeTag: String) = "$localeTag\n$text"
    }
}
